---
url: "https://pdv.varejonline.com.br/pdv/login"
database:
   host: "bd.varejonline.com.br:1521/vpsa"
   dbname: "vpsa"
   user: "vpsa"
   password: "vpsa"
users:
  admin:
    email: "pdvnovo"
    pass: "varejonline"